### ISSUE TITLE
Collection.count deprecation warning

### ISSUE THREAD

**Issue by Gustav0ar** [WebGangster/mongoose-paginate-v2#12]
Do you plan to fix the deprecation warning for using the this.count?

 DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

I'm using version 1.0.19

**Comment by aravindnc** [comment]
@Gustav0ar $where will not work if we don't use this.count()
So I'm looking for a solution and will be updating the package as early as possible.

**Comment by aravindnc** [comment]
@Gustav0ar There is no other option I guess, we need to remove the support for $where.

**Comment by Gustav0ar** [comment]
That's a shame, but fortunately $where isn't a requirement, just a helper for who likes to use SQL syntax

**Comment by aravindnc** [comment]
@Gustav0ar New version has been updated with the fix removing the $where support.
