### ISSUE TITLE
Support collation

### ISSUE THREAD

**Issue by Gustav0ar** [WebGangster/mongoose-paginate-v2#13]
**Is your feature request related to a problem? Please describe.**
At the moment when search or sort text, it doesn't support accents and other locale stuff

**Describe the solution you'd like**
Support collation
https://docs.mongodb.com/manual/reference/collation/

**Comment by aravindnc** [comment]
I will be adding this in the next version.
@Gustav0ar Thanks.

**Comment by aravindnc** [comment]
Collation support added and new package has been updated. You can pass `collation` inside options, 
```
var options = {
    sort: {
         _id: 1
    },
    collation: {
        locale: 'en',
        strength: 2
    }
};
```

Let me know if you have any questions.

**Comment by wishedy** [comment]
how to use populate

**Comment by aravindnc** [comment]
> how to use populate

Please see the other thread. I've explained it there. Thanks.
