### ISSUE TITLE
i don't understant how to use populate

### ISSUE THREAD

**Issue by wishedy** [WebGangster/mongoose-paginate-v2#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Arjun-Shinojiya** [comment]
@wishedy https://github.com/WebGangster/mongoose-paginate-v2/issues/16

**Comment by aravindnc** [comment]
@wishedy Here is an example,

```
var query = {
				title: { 
					$in : [/Book/i]
				}
		};
		
		var options = {
			sort: { _id: 1},
			populate: {
				path: 'author',
				match: {
					name: 'Arthur Conan Doyle'
				}
			},
			collation: {
				locale: 'en',
				strength: 2
			}
		};
		
      return Book.paginate({}, options ).then((result) => {
});
```

**Comment by aravindnc** [comment]
You can follow this for using populate,
https://mongoosejs.com/docs/populate.html

**Comment by wishedy** [comment]
Thanks for your advice. Because of the time difference, I am at 11 o 'clock at midnight. When I turn on the computer tomorrow, I will try. Thank you again, and the plug-in you provided, this problem has been bothering me.

**Comment by aravindnc** [comment]
@wishedy Thanks for using this. Feel free to open issues if you see anything. 
Regarding populate, you just have to pass the populate object after understanding https://mongoosejs.com/docs/populate.html 

Have a nice sleep.

**Comment by aravindnc** [comment]
@wishedy Hope you got it resolved.
Please reopen this thread if you have any questions.

**Comment by Leeiio** [comment]
[populate] {Array | Object | String} - Paths which should be populated with other documents. 

How can i use two populate actions?

**Comment by aravindnc** [comment]
@Leeiio You can pass populate object as an array. Below is an example,
```
let populateObj = [{
    path: 'user',
    model: 'User'
}, {
    path: 'role',
    model: 'Role'
}]
```

**Comment by Leeiio** [comment]
@aravindnc Thanks, but i can not find this usage in mongoose  doc. https://mongoosejs.com/docs/api.html#query_Query-populate

**Comment by aravindnc** [comment]
@Leeiio Please check https://mongoosejs.com/docs/populate.html
