### ISSUE TITLE
The latest version doesn't work for MongoDB v <3.4

### ISSUE THREAD

**Issue by ilyahumbar** [WebGangster/mongoose-paginate-v2#17]
Introduced recently collation support (#13) breaks backward compatibility with older MongoDB versions.

The following check is always true and doesn't actually serves its purpose described in the comment.
https://github.com/WebGangster/mongoose-paginate-v2/blob/fdd5aff180986018acd733c811f3fba4e40e08bc/index.js#L67-L70

**Comment by aravindnc** [comment]
@ilyahumbar Can you try the updated version 1.0.21

**Comment by ilyahumbar** [comment]
Yes. Works great. 
Thank you for your quick response!

**Comment by aravindnc** [comment]
@ilyahumbar Please feel to open a new thread if you see any issues. 
Cheers & Happy Coding!
