### ISSUE TITLE
Limit of zero returns all documents instead of just the metadata

### ISSUE THREAD

**Issue by rpkale** [WebGangster/mongoose-paginate-v2#19]
If limit is set to zero, all documents are returned instead of none.

This used to work earlier (at least till version 1.0.13) but
recent updates seems to have changed the behavior.

**Comment by aravindnc** [comment]
@rpkale Thanks. I will check and get back today.

**Comment by fernandolguevara** [comment]
@rpkale @aravindnc it seems to be a mongoose library bug

**Comment by aravindnc** [comment]
@fernandolguevara Yes. You seems to be right. It seems to be the default behavior of mongodb.

**Comment by aravindnc** [comment]
@rpkale May be we can try for other alternatives. Can you tell me your use case ?

**Comment by rpkale** [comment]
I did not update my mongodb/mongoose version but existing unit tests in our app started
failing after updating only mongoose-paginate-v2 to latest version. I had a unit test that was
testing the 'limit=0' case.

This is the way mongodb/mongoose always behaved but mongoose-paginate-v2 was designed
to behave differently. The documentation also reflected that:
'You can use `limit=0` to get only metadata:' (now removed from Readme?)

Earlier version of this module's code (July 18) implemented this by always doing a 
'count' promise but doing the 'docs' promise only if limit > 0.

Though the documented API changed, only the patch version got bumped up.
This may cause surprises to other users or introduce subtle bugs in their apps.

We use this module to provide pagination for our REST API. Zero was a supported 'limit' parameter
for our API. The unit tests verified that it worked as intended.  I can put a fix in our app
to have a workaround for the limit = 0  case (skipping the use of pagination module and getting
the count manually). Else I will have to change the API for our app and not allow users to use
a limit of zero. We don't want our REST API users to inadvertently retrieve thousands of documents.

It would be best if this module fixed this internally and provide the original behavior.
I think this is a useful 'feature' this module provides (an efficient way to retrieve the count of documents
without doing a full query).

**Comment by aravindnc** [comment]
@rpkale No worries, I can fix it today. Can you share me the expected outcome while doing limit=0 query. A sample JSON output would be appreciated.
Thanks.

**Comment by aravindnc** [comment]
@rpkale The issue is resolved. You can use limit=0 to get metadata only. Thanks for pointing out.
Please update to the latest version v1.0.23
