### ISSUE TITLE
Querying populated fields return empty array

### ISSUE THREAD

**Issue by ramoncardena** [WebGangster/mongoose-paginate-v2#21]
**Describe the bug**
When you query a subdocument that has been populated, the query returns empty array.

**To Reproduce**
1.- Create a Schema with populated fields.

```
const ProjectSchema = new mongoose.Schema(
    {
        name: {
            en: {
                type: String,
                required: true,
            },
            es: {
                type: String,
                required: true,
            },
        },
        maker: { type: ObjectId, ref: 'Maker' }
}
```
2.- Create an endpoint to retrieve items from the new model using paginate with a filter using a populated field:
```
const getItemsFromDB = async (req, query) => {
const options = {
        sort: 'createdAt',
        lean: true,
        1,
        5,
         { path: 'maker', select: 'name' },
    }
    return new Promise((resolve, reject) => {
        model.paginate(query, options, (err, items) => {
            if (err) {
                reject(buildErrObject(422, err.message))
            }
            resolve(cleanPaginationID(items))
        })
    })
}
```

3.- Call the endpoint querying the populated field:

`{{server}}/projects?filter={"maker.name":"Ocean Sentry"}&page=1&limit=2&sort=name&order=-1`

4.- Get an empty array in the results:

```
{
    "docs": [],
    "totalDocs": 0,
    "limit": 2,
    "hasPrevPage": false,
    "hasNextPage": false,
    "page": 1,
    "totalPages": 1,
    "pagingCounter": 1,
    "prevPage": null,
    "nextPage": null
}
```

**Expected behavior**
An array containing the results. If you query for a field with subdocuments (not populated) it works correctly.

**Comment by FreeDevStan** [comment]
I'm also get empty array. I'm trying to get all document's, but I get empty array. My model:
```
let Schema = new Schema({
    id : {type : Number, required : true},
    created : {type : Date, default: Date.now()},
    player : {type : ObjectId, ref : 'player', autopopulate: true},
    operator: {type: ObjectId, ref: 'operator'},
    events : Array,
    verified: Date
});

Schema.plugin(require('mongoose-autopopulate'));
Schema.plugin(require('mongoose-paginate-v2'))
```

**Comment by aravindnc** [comment]
@ramoncardena  Can you explain your options object. I'm not sure about the values other than sort and lean.

**Comment by aravindnc** [comment]
@FreeDevStan Can you share the output when page=1

**Comment by ramoncardena** [comment]
@aravindnc the options are just an example:
Sorting by creation date, lean true, order 1, limit to 5 and populate maker field selecting just name.
```
const options = {
        sort: 'createdAt',
        lean: true,
        1,
        5,
         { path: 'maker', select: 'name' },
    }

```

But I was going to update the post because I think what it's happening it's expected. Populate occurs after executing the query (find or paginate) so, the subdocument I'm referring for the query is not populated yet, so the query returns empty.

I think the solution is to use $lookup in aggregation before paginate, and that's what mongoose-aggregate-paginate-v2 does. So i'm trying it now to see if it works in my case.

**Comment by aravindnc** [comment]
@ramoncardena That's Cool. Let me know if you have any queries. 
Happy Coding!

**Comment by ramoncardena** [comment]
I can confirm that aggregate-paginate-v2 works for my case. So, as the docs say, for simple cases use mongoose-paginate-v2, but for more complex cases aggregate-paginate-v2 is the right choice.

I my case I created an aggregation:

```
const myAggregate = model.aggregate([
            {
                $lookup: {
                    from: 'makers',
                    localField: 'maker',
                    foreignField: '_id',
                    as: 'maker',
                },
            },
            {
                $unwind: '$maker',
            },
            { $match: query },
        ])
```
Where I use $lookup to 'join' the subdocument filled by populate before (maker). Then I use $match to apply the query and after that you can call aggregatePaginate in your model: 

```
model.aggregatePaginate(myAggregate, options, (err, items) => {
            if (err) {
                reject(buildErrObject(422, err.message))
            }
            resolve(cleanPaginationID(items))
        })

```

**Comment by aravindnc** [comment]
@ramoncardena Great. Cool.
You have to edit the write-up there is a typo,
```
for more complex cases mongoose-aggregate-paginate-v2 is the right choice.
```

**Comment by aravindnc** [comment]
@FreeDevStan Let me know if the issue still persists or if you have any question.

**Comment by otaviobps** [comment]
Hi @ramoncardena how did you do your query? I'm getting an empty array when I try to query a field of the populated collection:

```
const myAggregate = Order.aggregate([
      {
        $lookup: {
          from: "users",
          localField: "user",
          foreignField: "_id",
          as: "user"
        }
      },
      {
        $unwind: "$user"
      },
      {
        $match: { user: { firstName: "Francisco" } }
      }
    ]);
```
If I skip the query, I get the fields populated, so I'm sure is something with the query. I'm using the `mongoose-aggregate-paginate-v2`, however I can't query from a populated field.

Thanks!
