### ISSUE TITLE
mongoosePaginate.paginate.options doesnt take effect when I use someModel.paginate()

### ISSUE THREAD

**Issue by abnervieraso** [WebGangster/mongoose-paginate-v2#22]
Sorry for my english, but I'll try to explain this, Im new and this is my first report in my life :( :

**Describe the bug**
When I trying to set **set custom default options for all queries** and then use someModel.paginate() mongoose returns all data but the the default custom options doesnt not take effect, but when I set directly options to 'paginate()' params: example myModel.paginate({}, {someOptions}), the options works correctly. 

**To Reproduce**
1. Set custom options for all queries (in my case, I add the mongoosePaginate.paginate.options directly to 'user' controller however i've tried to add as config.js file and other ways but it doesnt work)
2. Do a query with paginate without params, like myModel.paginate() (its supposed that paginate() method will get the default options that i did set)
3. The method returns all data... Does not take the options that I did set

**Expected behavior**
The data filtered by the options

**Screenshots**

![photo1](https://user-images.githubusercontent.com/45499791/53978409-c391d380-40d0-11e9-898b-ca949a620c19.png)

![photo2](https://user-images.githubusercontent.com/45499791/53978428-cd1b3b80-40d0-11e9-92a9-c60e5371b179.PNG)

As you can see in the last image, the data have not the options that i did set.

**Desktop (please complete the following information):**
 - OS: Win 10 
 - Browser: Postman
 - Version: Node v.10.15.1

**Additional context**
**Hey, I've been trying with the first version of mongoose-paginate, and this problem doesn't appear, its so strange**
but i dont want to use the first version.

**Comment by aravindnc** [comment]
@abnervieraso Thanks for reporting this. I saw the issue now and I will be adding a fix tomorrow. Is that okay for you?

**Comment by abnervieraso** [comment]
> @abnervieraso Thanks for reporting this. I saw the issue now and I will be adding a fix tomorrow. Is that okay for you?

It's ok, thank you and happy coding.

**Comment by aravindnc** [comment]
@abnervieraso The issue has been resolved. Please use the latest package.

**Comment by nengine** [comment]
Sorry, I am posting here unrelated issue here.  Any help is appreciated on how to use async/await something like.

```js
var result = await Model.paginate()
```
