### ISSUE TITLE
Add paginator elements in an object

### ISSUE THREAD

**Issue by Tititrois** [WebGangster/mongoose-paginate-v2#23]
Is it possible to have an option to add all elements in a json object instead of placing them in the root of the result?

> From this: 

```
{
 docs: [...],
  totalDocs: 10,
  limit: 5,
  page: 1,
  totalPages: 2,
  pagingCounter: 11,
  hasPrevPage: true,
  hasNextPage: false,
  prevPage: 2,
  nextPage: null 
}
```

> To this:

```
{
 docs: [...],
 paginator: {
   totalDocs: 10,
   limit: 5,
   page: 1,
   totalPages: 2,
   pagingCounter: 11,
   hasPrevPage: true,
   hasNextPage: false,
   prevPage: 2,
   nextPage: null 
 },
}
```

Thanks !

**Comment by aravindnc** [comment]
@Tititrois Can you tell me what exactly is your requirement.

**Comment by Tititrois** [comment]
A solution I would enjoy is the ability to provides two labels in the options object to receive a personalized response:
- the first label changes the 'docs' field containing the data  
- the second one envelop all elements of the paginator in an label.

Example:

- The options object:

[options] {Object}
[select] {Object | String} - Fields to return (by default returns all fields). Documentation
[collation] {Object} - Specify the collation Documentation
...
**[dataLabel]** {String} - Change the label enveloping the data
**[paginatorLabel]** {String} - Envelop the paginator metadata inside a json element

And so, if I provide the following options:
```
const options = {
    dataLabel: 'customData',
    paginatorLabel: 'paginatorData,
};
```

It's giving the following response:
```
{
 dataLabel: [...],
 paginatorData: {
   totalDocs: 10,
   limit: 5,
   page: 1,
   totalPages: 2,
   pagingCounter: 11,
   hasPrevPage: true,
   hasNextPage: false,
   prevPage: 2,
   nextPage: null 
 },
}
```

Do you think it is possible to implement that ? Otherwise I can manage it myself, but I think it would be cleaner to have this feature in the library directly.

**Comment by Tititrois** [comment]
I just realized I missed i nthe documentation we can already personalized the name for 'docs'. Is it possible to add in this array a new value for the customLabelPaginator as describes in my message previously.
It could be added either in the options directly (like in my last message), or maybe in 'mycustomlabels' ?

Or second options there:
```
const myCustomLabels = {
    totalDocs: 'itemCount',
    docs: 'itemsList',
    limit: 'perPage',
    page: 'currentPage',
    nextPage: 'next',
    prevPage: 'prev',
    totalPages: 'pageCount'
    pagingCounter: 'slNo',
    
    paginatorData: 'customLabelPaginator',
};
```

**Comment by aravindnc** [comment]
@Tititrois Sorry for the delay. Let me see what I can do.

**Comment by jaysalvat** [comment]
Feature added to PR #31 if merged.

**Comment by aravindnc** [comment]
@Tititrois This feature has been added.
Thank you for the contribution @jaysalvat
