### ISSUE TITLE
Cast error on the "limit" option

### ISSUE THREAD

**Issue by Tititrois** [WebGangster/mongoose-paginate-v2#24]
**Describe the bug**
I'm not sure if it's wanted or not, but I will still report it. When submitting the mongoose request, if the limit option is a string (for example "10"), it's returning an error. In my case, I receive the option list from some query params and thus, they are in a String format event for integer. 
It's happening only for the limit option (page is working fine with a string).

**To Reproduce**
Simply submit a mongoose paginate request follow the description above.

**Expected behavior**
Can the library do the integer cast for the limit option ?

**Comment by aravindnc** [comment]
@Tititrois  Thanks for pointing this out.

**Comment by aravindnc** [comment]
@Tititrois This has been fixed.

**Comment by Tititrois** [comment]
Thanks !
