### ISSUE TITLE
customLabels

### ISSUE THREAD

**Issue by kerolloz** [WebGangster/mongoose-paginate-v2#28]
**Describe the bug**
using custom labels, if you want for example to do the following `customLabels: {
      docs: 'posts'
    } ` this will result into discarding the other properties  

**To Reproduce**
1.  `  const options = {
customLabels: {
      docs: 'posts'
    }
  };
`

**Expected behavior**
all the properties should exist 

**Screenshots**
![image](https://user-images.githubusercontent.com/36763164/56972734-cad2dc00-6b6b-11e9-8c95-7c890c193b51.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Postman

**Comment by aravindnc** [comment]
@kerolloz Thanks for pointing out. The issue has been resolved and I will publish the patch tomorrow.
