### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by pak11273** [WebGangster/mongoose-paginate-v2#29]
**Describe the bug**
Output is false.
{
 totalDocs: 5,
  limit: 3,
  hasPrevPage: false,
  hasNextPage: false,
  page: NaN,
  totalPages: 2,
  pagingCounter: NaN,
  prevPage: null,
  nextPage: null
}

The output doesn't even make sense.
 
**To Reproduce**
options: {
  page: 1,
  lean: true,
  limit: 3,
  collation: {
    locale: 'en'
   }
}

**Expected behavior**
{
 totalDocs: 5,
  limit: 3,
  hasPrevPage: false,
  hasNextPage: true,
  page: 1,
  totalPages: 2,
  pagingCounter: 1,
  prevPage: 1,
  nextPage: 2
}

**Comment by aravindnc** [comment]
@pak11273 
I've tested it with the option you've shared and seems to be working well. 
Below is my output.

```
{
  docs: [{
      _id: 5 cccfe63b641c377585b0cd0,
      price: 6,
      title: 'Book #1',
      date: 2019 - 05 - 04 T02: 52: 19.532 Z,
      author: 5 cccfe63b641c377585b0ccf,
      __v: 0,
      id: '5cccfe63b641c377585b0cd0'
    },
    {
      _id: 5 cccfe63b641c377585b0cd1,
      price: 12,
      title: 'Book #2',
      date: 2019 - 05 - 04 T02: 52: 19.533 Z,
      author: 5 cccfe63b641c377585b0ccf,
      __v: 0,
      id: '5cccfe63b641c377585b0cd1'
    },
    {
      _id: 5 cccfe63b641c377585b0cd2,
      price: 18,
      title: 'Book #3',
      date: 2019 - 05 - 04 T02: 52: 19.534 Z,
      author: 5 cccfe63b641c377585b0ccf,
      __v: 0,
      id: '5cccfe63b641c377585b0cd2'
    }
  ],
  totalDocs: 100,
  limit: 3,
  hasPrevPage: false,
  hasNextPage: true,
  page: 1,
  totalPages: 34,
  pagingCounter: 1,
  prevPage: null,
  nextPage: 2
}
```

Please try again.

**Comment by pak11273** [comment]
Okay supplying the page number a null value got me this error.  Thanks for looking at this.

**Comment by pak11273** [comment]
Just a side question.  Have you tested this on scale? (ie. 100,000+ users)

**Comment by aravindnc** [comment]
@pak11273 Not really. I had a chance to test with with 1000 users max.

**Comment by pak11273** [comment]
No problem.  Good work on the library!
