### ISSUE TITLE
hasPrevPage and hasNextPage configurable

### ISSUE THREAD

**Issue by jaysalvat** [WebGangster/mongoose-paginate-v2#30]
Hello and thanks for sharing this lib :)

Why hasPrevPage and hasNextPage can't be changed?
Lot of APIs use a snake_case field naming as has_next_page / has_prev_page.

Thanks a lot.

**Comment by aravindnc** [comment]
@jaysalvat Thanks for pointing out. I will make hasPrevPage/hasNextPage also configurable.

**Comment by jaysalvat** [comment]
Thanks a lot!

Don't worry.
I'm working on some improvements right now.
I will make a pull request with this fix too.

**Comment by jaysalvat** [comment]
As promised, here is the PR #31 fixing this issue.
