### ISSUE TITLE
How to set limit = infinite?

### ISSUE THREAD

**Issue by ajmas** [WebGangster/mongoose-paginate-v2#33]
**Is your feature request related to a problem? Please describe.**

For certain specific situations I would like to be able to disable the limit, without needing to use find(). I did not see in the documentation if this was possible. I did try '-1' and 'undefined' as values, but neither worked.

Somewhere 'undefined' appears to be treated as zero, since the `perPage` values comes back as 0.

**Describe the solution you'd like**

Some method to disable the limit. Either via a value to the `limit` option or an explicit option.

**Describe alternatives you've considered**

 - Duplicating logic with find()

**Additional context**

**Comment by aravindnc** [comment]
@ajmas Can you share your expected output while doing limit as infinite.

**Comment by ajmas** [comment]
I suppose it would be to act as if paging was disabled. 

Thinking some more yesterday, another  workaround is simply to use an arbitrarily large limit.

**Comment by aravindnc** [comment]
@ajmas Cool. Hope that serves your purpose.

**Comment by nyce-gh** [comment]
The [mongodb-documentation](https://docs.mongodb.com/manual/reference/method/cursor.limit/#zero-value) says 

> A limit() value of 0 (i.e. .limit(0)) is equivalent to setting no limit.

It seems that this was possible with this plugin, too - until #19.

It would make sense to comply with the standard. Using the listed tricks (like setting a very large limit or disabling the complete pagination) doesn't feel good.
