### ISSUE TITLE
Sort case insensitive option

### ISSUE THREAD

**Issue by kamaral75** [WebGangster/mongoose-paginate-v2#34]
**Is your feature request related to a problem? Please describe.**
MongoDB sorts case sensitive by default. Sorted results are returned in case-sensitive order, so capital 'Z' is ordered before lowercase 'a'. It would be great to have an option to sort alphabetically in case-insensitive order.

**Describe the solution you'd like**
Create an option to set the 'sort' to be case insensitive.

**Comment by kamaral75** [comment]
Ah, this is already supported with the collation option. Thank you for creating such a useful module!

https://stackoverflow.com/questions/56708171/mongoose-pagination-case-insensitive-string-sorting/56710622#56710622

**Comment by aravindnc** [comment]
@kamaral75 Thank you for the support.
