### ISSUE TITLE
If page is more than totalDocs then empty array

### ISSUE THREAD

**Issue by ruslanguns** [WebGangster/mongoose-paginate-v2#35]
**Describe the bug**
If I am sending higher page returns empty array. 

**To Reproduce**
Data object is the result from query using paginate-v2. As you can see limit is fine asking for more data in the query, the issue only happens with page (per_page).

**Expected behavior**
Should return last page available, or validation error.

**Screenshots**
![image](https://user-images.githubusercontent.com/19806968/61012330-f9dca980-a375-11e9-94f2-bd4ced370466.png)

**Desktop (please complete the following information):**
 - OS: Windows Node NestJS

**Comment by aravindnc** [comment]
@ruslanguns 
You can always check hasPrevPage/NextPage OR totalPages to see if next page has data or not.

**Comment by ruslanguns** [comment]
Can you please show me an example of this validation?

**Comment by aravindnc** [comment]
I mean do not snow page 2 if you get hasNextPage = false while getting response from page = 1.
ie. 
if hasNextPage == true 
then load next page
else stop loading further pages

**Comment by ruslanguns** [comment]
Oh yes, I understand the work around, I am actually printing an Exception Error when someone is paging to pages that does not exists, however my guess it that the library should validate this arg with a default action as a default, for example, show the last page possible.
