### ISSUE TITLE
Provide Cursor itself

### ISSUE THREAD

**Issue by mkastner** [WebGangster/mongoose-paginate-v2#36]
**Is your feature request related to a problem? Please describe.**
I'd like to resolve the paginated result in GraphQL. Therefor I need a Cursor.

**Describe the solution you'd like**
Providing the Cursor itself.

**Describe alternatives you've considered**
Using primary keys as cursors in order to resolve to edges in GraphQL, but that's considered problematic.

**Comment by aravindnc** [comment]
@mkastner  Can you share the proposed output format.

**Comment by aravindnc** [comment]
Please reopen if needed.
