### ISSUE TITLE
 TypeError: this.countDocuments is not a function

### ISSUE THREAD

**Issue by buitranduong** [WebGangster/mongoose-paginate-v2#44]
at Function.paginate (/app/node_modules/mongoose-paginate-v2/dist/index.js:104:27)

My Model 

const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate-v2');
const CustomersDraftSchema = new mongoose.Schema({
.........
});
CustomersDraftSchema.plugin(mongoosePaginate);
module.exports = mongoose.model('customers_draft', CustomersDraftSchema);

**Comment by aravindnc** [comment]
@buitranduong Seems to be something wrong with the model.

**Comment by aravindnc** [comment]
@buitranduong Please try the new version and see if the issue exists.
